### ISSUE TITLE
Update runtime to Spine 4.1 

### ISSUE THREAD

**Issue by britzl** [defold/extension-spine#88]
http://esotericsoftware.com/blog/Spine-4-1-released

**Comment by Ragetto** [comment]
Hey @britzl ! When do you think this update will be available?

I've been working on Spine animations for the last 10 days,  updated Spine to 4.1 in the process (stupid I know).

And now I can't use my dozens of animations since Defold won't read the 4.1 spine_json export :(

Anyway... I'll work on other aspects in the meantime, but can't wait for this update... :')

**Comment by JCash** [comment]
Well, we're currently on vacation now for the upcoming week.
Maybe some other team members may find some time to look at it.

However, in the meantime, I suggest downgrading your Spine editor to 4.0.
You can also into creating a PR yourself, or asking the community for help.

**Comment by britzl** [comment]
> When do you think this update will be available?

I created this GitHub ticket as a reminder that there is a new runtime. We have no immediate plans to update the runtime and extension.

**Comment by britzl** [comment]
Script to build the runtime can be found here: https://github.com/defold/extension-spine/blob/main/utils/runtime/build_runtime_lib.sh (and which version to use)
